[package]
name = "granular"
version = "0.0.1"
authors = ["Manuel Deval <manuel.deval@gmail.com>"]
edition = "2018"

[dependencies]
dsp = { path = "../dsp" }
crossbeam = "0.8.0"
strum = "0.20"
strum_macros = "0.20"

[lib]
path="src/lib.rs"